name: ks-docs
region: sfo
domains:
  - domain: docs.knowledgestack.ai
    type: PRIMARY
static_sites:
  - name: docs
    github:
      branch: main
      deploy_on_push: true
      repo: knowledgestack/ks-docs
    source_dir: /
    environment_slug: node-js
    build_command: npm run build
    output_dir: out
